### ISSUE TITLE
Basic OG Tags for link previews, and page titles

### ISSUE THREAD

**Issue by awlevin** [ThinkFiveable/open#10]
Current link previews look like this:

<img width="511" alt="Screen Shot 2021-03-20 at 5 46 32 PM" src="https://user-images.githubusercontent.com/8488209/111887617-36aecf80-89a4-11eb-9c9d-fa1584557004.png">

Similar opportunity to improve page titles:

<img width="259" alt="Screen Shot 2021-03-20 at 5 47 04 PM" src="https://user-images.githubusercontent.com/8488209/111887623-49c19f80-89a4-11eb-93ba-acd523924b2c.png">

Might as well add a `<meta description="..."/>` while we're at it, since Google will likely be able to pick this up :)

**Comment by sarthaktexas** [comment]
Ya it's all there in the `head.js` file just change the variables and add an image.

**Comment by sarthaktexas** [comment]
anybody feel free to do this!

**Comment by TejasCreative** [comment]
Yeah I was planning on doing this b/c I'm still a noob and learning + this is pretty easy
