### ISSUE TITLE
Unfinished Card Component

### ISSUE THREAD

**Issue by sarthaktexas** [ThinkFiveable/open#15]
Whoever gets assigned this should finish the Card Component according to the design specifications on the Figma. Make sure you put the component on the index.js page with some dummy data, so we can see it in the Preview Deployment.

**Comment by exu3** [comment]
I can go ahead and finish it since I started it

**Comment by sarthaktexas** [comment]
thanks ella, tag me in discord or slack if you need any help. you don't need to add the second variant of this component just yet but make sure to add a prop for the gold, silver, and bronze outlines.

**Comment by zaida04** [comment]
This should have been closed when #23, no clue why it didn't. Perhaps the pr title name shouldn't be between the close keyword and the reference id.
