### ISSUE TITLE
Contributor component

### ISSUE THREAD

**Issue by exu3** [ThinkFiveable/open#20]
create the contributor component in the components directory
![Screenshot (15)](https://user-images.githubusercontent.com/72365100/111932983-c5dae680-8a7b-11eb-8ac7-bf2409a91612.png)

**Comment by zaida04** [comment]
For the MVP, we can hard code this. But later on, we should consider dynamically pulling data for this component straight from github api itself.

**Comment by sarthaktexas** [comment]
I don't think it should be hard coded at all. The API specifications aren't difficult, they just require an auth key.

**Comment by sarthaktexas** [comment]
@zaida04 figured it out, here's the endpoint so just `useSWR('https://api.github.com/repos/thinkfiveable/open/contributors')` it and add it to the function, whoever does it.
