### ISSUE TITLE
Card component

### ISSUE THREAD

**Issue by exu3** [ThinkFiveable/open#21]
this is the second variant of the project card component
![card component](https://user-images.githubusercontent.com/72365100/111933474-caec6580-8a7c-11eb-86b9-bc22302adbbb.png)

**Comment by jasonappah** [comment]
If no-one is working on this I can take this issue.

**Comment by exu3** [comment]
Awesome, thanks Jason!

**Comment by zaida04** [comment]
How's the progress on this? Is this still needed at this point, the other design works fine for us. I _would be open_ to mixing and matching card components.

**Comment by jasonappah** [comment]
It's been done - see #37. I still need to make the card responsive tho
