### ISSUE TITLE
Footer component

### ISSUE THREAD

**Issue by exu3** [ThinkFiveable/open#22]
Create the footer component according to the design specifications on the Figma. You can put the component on the index.js page afterwards, so we can see it in the preview deployment.

**Comment by sarthaktexas** [comment]
Can you attach a screenshot @eilla1?

**Comment by sarthaktexas** [comment]
Whoever does this, make sure the wave is made with an SVG. This should be a flex box w/ column with the SVG on top and a Fiveable Black (#171717) rectangle below. Otherwise, when we animate this in the future, it won't be easy.

**Comment by exu3** [comment]
![footer](https://user-images.githubusercontent.com/72365100/111934457-adb89680-8a7e-11eb-97ec-ffed74ee215e.png)
