### ISSUE TITLE
Link to the repo from the site

### ISSUE THREAD

**Issue by awlevin** [ThinkFiveable/open#25]
To make it easier to navigate the project & get started contributing, there should be a link to the repo from the main site.

Do we need to update designs before this issue is ready to be picked up? Not sure what the workflows should look like with design (do we make a new label for "design needed" ?)

**Comment by sarthaktexas** [comment]
I will add this to the site design. Any preferred locations for the icon?

**Comment by exu3** [comment]
Perhaps in the top right so it's easy to find?

**Comment by awlevin** [comment]
And maybe just a Github icon so it doesn't take up too much space?

**Comment by awlevin** [comment]
<img width="141" alt="Screen Shot 2021-03-22 at 5 24 58 PM" src="https://user-images.githubusercontent.com/8488209/112065967-8f60a280-8b33-11eb-9d1e-90db2f2fc1c6.png">

Actually, just saw this nifty widget on https://hasura.com

**Comment by sarthaktexas** [comment]
I was thinking of that actually lol @awlevin
