### ISSUE TITLE
DARK MODE

### ISSUE THREAD

**Issue by sarthaktexas** [ThinkFiveable/open#29]
If you want to add dark mode to the site, please dm me on Slack or Discord, and we can make a design together, and you can code dark mode in using the `dark:` utility. This should be too hard, but I don't want to keep requesting changes without a design so let me know.

**Comment by ceelo777** [comment]
I'm down to do this if you want.

**Comment by ronaldleung1** [comment]
Hi, can you assign this issue to me? Would love to work on this too 👉👈
