### ISSUE TITLE
ci workflows

### ISSUE THREAD

**Issue by zaida04** [ThinkFiveable/open#4]

**Comment by jasonappah** [comment]
I can take this if no-one is currently working on it. Should I just add a workflow for running a test build? It might also be a good idea to add a `.prettierrc` and `.eslintrc` so we can keep code style consistent.

**Comment by zaida04** [comment]
Yep! Thank you for taking this, we’d love it if we could have the eslintrc extend some industry standard templates like Marine and such. Keep in mind we are also planning to use TypeScript, so adapt the eslintrc to support it (see: typescript-eslint plug-ins).

For the workflow you decide which one is better:
- two workflows, one for linting and one for building
- one workflow, takes care of both linting and building
