### ISSUE TITLE
optimize the various data holders

### ISSUE THREAD

**Issue by zaida04** [ThinkFiveable/open#42]
We currently hard code the data for `./data/PROJECTS.json` and `./data/CONTRIBUTORS.json`. In the future, post MVP stage, I'd like to dynamically fetch this data, either from the Github API or our own proxy (probably overcomplicating this).

This is finally where the backend bois rise up.

**Comment by rayhanadev** [comment]
Hiya! I'm pretty familiar with the Github API, so I was wondering if you might want some help automating project data?

**Comment by zaida04** [comment]
Totally, to get started you can use getStaticProps/useSWR and fetch the JSON file from Github API. I'll go ahead and assign this to you.

**Comment by rayhanadev** [comment]
Awesome!

**Comment by rayhanadev** [comment]
So @zaida04 I'm curious what data you might be looking for. From what I can tell in `./data/PROJECTS.json` you will need to get the repo's owner and the owner's profile picture. In addition I can also pull any tags/repo topics from the repo, the homepage url, an updated-at date, and the open-graph image if it has one.

Are you looking for anything else? I can certainly get more if you need some!

**Comment by zaida04** [comment]
Preferably, we want to only have to store as minimal amount of data as needed, `repo owner, repo name, an optional thumbnail, type, and award`. 

We actually generate the repo owner and profile picture urls on our own since the above data is sufficient to form them. It's just `https://github.com/OWNER` and `https://avatars.githubusercontent.com/USER`.

I'm welcome to having tags/topics, updatedAt date, and maybe things like star & fork count. I'm weary of using the homepage URL since we don't really have a way of verifying the content on those pages, and the open-graph github images thing is still being rolled out and is not available on 100% of repos yet to my knowledge.

**Comment by rayhanadev** [comment]
> We actually generate the repo owner and profile picture urls on our own...

Oh cool, I didn't know about that :D.

> ...the open-graph github images thing is still rolling out...

Really, I thought it came out [some time back](https://github.blog/2019-04-17-custom-open-graph-images-for-repositories/). I'll look into it some more and do a bit of research.

Alrighty, I'll add in the basic items and we can expand it from there. That's the beauty of a GraphQL API.

**Comment by zaida04** [comment]
> > ...the open-graph github images thing is still rolling out...
> 
> Really, I thought it came out [some time back](https://github.blog/2019-04-17-custom-open-graph-images-for-repositories/). I'll look into it some more and do a bit of research.

Oh haha, I thought you were referring to the Open Graph _generated previews_ such as:

![preview](https://images-ext-1.discordapp.net/external/VyRg3ahCtRkuCE7mNMXDrGHTWE-MjnP5t0TT0Vk9S5M/https/opengraph.githubassets.com/e436fcf8b8e9bfc04a87509e2fdfe84f0e596e3d8271999396a0a9108bb5fc47/ThinkFiveable/open)

**Comment by rayhanadev** [comment]
Oh nonono I meant the repo image xD. Sorry if I wasn't clear on that lol.

**Comment by rayhanadev** [comment]
Hey @zaida04 what are you doing for environment variables (assuming you're using environment variables in this project). Using the Github API requires a personal access token and I don't want to commit my own, but I can't deploy a preview without a token :/.

**Comment by zaida04** [comment]
Hmmm, what data are you trying to get that requires this personal access token? This could be due to it being the GraphQL API, as using the REST `/repos/:OWNER/:REPO` endpoint doesn't require a token of any kind. If this is the case, i'd prefer we switch over to the REST API instead. The payloads aren't that large anyways so it isn't that big of a deal for us, especially since it's just a SSR site that only needs to refresh this data periodically server-side. If we were doing this operation on the client side then I'd be fine with using the GraphQL API for it.

If you feel it's necessary that we stick with the GraphQL API, I'll have the org generate a token that'll be used in the CI secrets and create an env file.

**Comment by rayhanadev** [comment]
You're correct it's just that since it's GraphQL the API requests a personal access token.

I'll try switching some code over to the REST API and update you on how it goes, however I feel the need to still support GraphQL and encourage your team due to the simplicity of GraphQL requests. Anyways, I'll work on it and let you know sometime.

**Comment by zaida04** [comment]
Hey, any update on this?

**Comment by rayhanadev** [comment]
Yeah sorry as I figure you know I've been cramming (\*oof\*). Probably going to continue after my school lays AP and State testing on me after this week. I have sourced the API endpoints, it's just a matter of implementation :).

**Comment by rayhanadev** [comment]
Heya @zaida04, I got back to working on this. I cloned the GraphQL fetching function and transformed it into a Restful fetching function (I'll include both in the final PR, so it'll be up to y'all). Progress 🎉!

It works, *however* the Restful API has a lower rate limit for unauthenticated requests. I'm not sure if that will be a problem since I'm working in the dev server which refreshes/refetches props on each change but I hit the rate limit within a few changes. Just letting you know :).

FYI: To make things clear I'm getting the data in `getStaticProps()`

**Comment by rayhanadev** [comment]
@zaida04 just following up, I hit the rate limit relatively quickly for the Rest API since I'm using unauthenticated requests. It's probably since I use the dev server so it refreshes props on code changes, but should I do anything to change that or do you think it'll be fine in prod?

**Comment by zaida04** [comment]
I think for the most part, it'll be fine in prod. The intention is to have this cached data refreshed like every 15 mins, so if you could implement that when you do the data fetching part, then ratelimits shouldn't be an issue.

**Comment by rayhanadev** [comment]
Okay, I can do that! I'll get back to you soon with some results :)
