### ISSUE TITLE
Project Cards - Details View & Links

### ISSUE THREAD

**Issue by awlevin** [ThinkFiveable/open#50]
Thought we had links from project cards to the individual repositories in an open PR but seeing as there are currently no PRs open and no links on the cards on open.fiveable.me, I guess we still need that!

This issue can be separated into 2 separate PRs if desired:
- [ ] Add links to project preview cards so it's easy to visit each project repo.
- [ ] Add a details view for the project cards so it's easy to see a quick synopsis of the project without diving in. Submissions in the Google form should already have this information, so minimal work needed there to flow it into the site.

For the details view, I think this could be a great opportunity to experiment with animations or CSS tricks. A couple ideas:
- A slide-out dark background on hover with white text.
- A card-flip animation on hover. There's a free tutorial preview of this in this course: [Natours Project — Using Advanced CSS and Sass (Part 2)](https://www.udemy.com/course/advanced-css-and-sass/) ("Building the Tours Section - Part 1/2/3"). I'm sure there's also libraries out there to make this a piece of cake. 
- A pop-out modal or some kind of FLIP transformation on the card. See [react-flip-toolkit](https://github.com/aholachek/react-flip-toolkit) (personal favorite of mine— very powerful & very easy to use, at least depending on what you're doing). Tutorial for it [here](https://alex.holachek.com/rft-tutorial/#0).

**Comment by exu3** [comment]
👀 cool ideas! I can take a stab at the details view later this week
