### ISSUE TITLE
git tutorials

### ISSUE THREAD

**Issue by zaida04** [ThinkFiveable/open#6]

**Comment by awlevin** [comment]
Would be cool if we used something [like this](https://alex.holachek.com/rft-tutorial/#0) (`mdx-deck`, that is). Unless anyone has other ideas! 

Would it maybe make sense to put instructions in a JSON array (or .yml file) so we could swap in / out different modes of presentation? 🤔

**Comment by julialding** [comment]
I can take this, but would love someone to collaborate with

**Comment by exu3** [comment]
> I can take this, but would love someone to collaborate with

I'd love to collaborate with you on this :D

**Comment by zaida04** [comment]
Thank you to the both of you for taking this. Some topics I think should be covered are: `clone`, `pull`, `commit`, `push`, `merge (like merge master into working branch)`, and how to resolve merge commits. Feel free to throw your own ideas into the pot.
