### ISSUE TITLE
Project Submission Form on Website

### ISSUE THREAD

**Issue by rayhanadev** [ThinkFiveable/open#74]
Instead of redirecting to third-party Google Forms, perhaps use something like [Formik](https://formik.org/). It's super easy to use and you can drop some styles and bam! Easy to make form. Probably also setup an API path and some notification service (maybe emailing with [nodemailer](https://nodemailer.com/about/)?)

**Comment by zaida04** [comment]
Hello! The google form was just for us to use while we got this repo off the ground. The intention now for the submitting process is for people to **open a PR here and add their project details to [projects.json](https://github.com/thinkfiveable/open/blob/main/data/PROJECTS.json).** A workflow similar to [js-org](https://github.com/js-org/js.org). We will add more details about this soon.

If you'd like to work on it, we're open to a PR on some draft steps for submissions. 👀

**Comment by rayhanadev** [comment]
@zaida04 ohhh okay gotcha.

I'll see what I can do :D.

**Comment by rayhanadev** [comment]
@zaida04 out of curiosity what are awards? I'm working on writing up submission tasks but I'm not sure how to explain what awards are and what one should do about them.

**Comment by zaida04** [comment]
Awards are the outlines that projects will have on our website. We haven't given them a purpose yet, but they're not something the submitters will set, it's something us (the maintainers) will "award" to their projects for whatever criteria we decide upon in the future.

**Comment by rayhanadev** [comment]
Got it, so when a user submits a project they will simply omit that field?

**Comment by zaida04** [comment]
Correct
