### ISSUE TITLE
Add semantic styles to links

### ISSUE THREAD

**Issue by rayhanadev** [ThinkFiveable/open#76]
When I generally see a link I expect that it has an underline, as is the general internet semantic with links, however on the MDX rendered documents there doesn't seem to be any styles added to links except bolding because of \*\*...\*\*.
![page](https://user-images.githubusercontent.com/72509475/119239970-68622500-bb12-11eb-9d38-b636bcb7ad75.jpeg)

The reason I recognize they link somewhere (besides being curious enough to click) is because you use action words such as "this" or "here" or a URL schema-like text is present. This may be fine in this situation (to an extent) but it is generally a better idea to have underlines when styling links.

Possible fixes:
- Add underlines to links
- Maybe change the color to a different one (blue?) to provide contrast and make them stand out

**Comment by awlevin** [comment]
Totally agreed! Feel free to make a PR addressing this how you see fit! Maybe ideally something that can set a global theme for how <a \> tags / elements should be styled?

**Comment by rayhanadev** [comment]
@awlevin sure thing :)!
